# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-26 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RFI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('client_address', models.CharField(blank=True, max_length=200, null=True)),
                ('client_address2', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('client', models.CharField(max_length=250, null=True)),
                ('today_date', models.DateTimeField(auto_now_add=True)),
                ('rfi', models.CharField(max_length=7, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('user', models.CharField(max_length=200, null=True)),
                ('info_requested', models.TextField(max_length=250, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('response', models.TextField(max_length=500, null=True)),
                ('user_signature', models.CharField(max_length=200, null=True)),
                ('client_signature', models.CharField(max_length=200, null=True)),
                ('user_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
